-- AlterTable
ALTER TABLE "ULB" ADD COLUMN     "latitude" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "longitude" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ALTER COLUMN "id" DROP DEFAULT;
DROP SEQUENCE "ULB_id_seq";

-- CreateTable
CREATE TABLE "ULBMaster" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "ULBMaster_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ULB" ADD CONSTRAINT "ULB_id_fkey" FOREIGN KEY ("id") REFERENCES "ULBMaster"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
